#############################################################################
# Makefile for building: adb-manager
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  adb-manager.pro
# Template: app
# Command: /home/gabriel/.programas/qt/5.15.2/gcc_64/bin/qmake -o Makefile adb-manager.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../.programas/qt/5.15.2/gcc_64/include -I../../../../.programas/qt/5.15.2/gcc_64/include/QtQuick -I../../../../.programas/qt/5.15.2/gcc_64/include/QtGui -I../../../../.programas/qt/5.15.2/gcc_64/include/QtQmlModels -I../../../../.programas/qt/5.15.2/gcc_64/include/QtQml -I../../../../.programas/qt/5.15.2/gcc_64/include/QtNetwork -I../../../../.programas/qt/5.15.2/gcc_64/include/QtCore -I. -I/usr/include/libdrm -I../../../../.programas/qt/5.15.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/gabriel/.programas/qt/5.15.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/gabriel/.programas/qt/5.15.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/gabriel/.programas/qt/5.15.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = adb-manager1.0.0
DISTDIR = /home/gabriel/Projetos/Develop/Qt\ Creator/ADB\ Manager/.tmp/adb-manager1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/gabriel/.programas/qt/5.15.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/gabriel/.programas/qt/5.15.2/gcc_64/lib/libQt5Quick.so /home/gabriel/.programas/qt/5.15.2/gcc_64/lib/libQt5Gui.so /home/gabriel/.programas/qt/5.15.2/gcc_64/lib/libQt5QmlModels.so /home/gabriel/.programas/qt/5.15.2/gcc_64/lib/libQt5Qml.so /home/gabriel/.programas/qt/5.15.2/gcc_64/lib/libQt5Network.so /home/gabriel/.programas/qt/5.15.2/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		run_command.cpp qrc_qml.cpp \
		moc_run_command.cpp
OBJECTS       = main.o \
		run_command.o \
		qrc_qml.o \
		moc_run_command.o
DIST          = ../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		adb-manager.pro run_command.h main.cpp \
		run_command.cpp
QMAKE_TARGET  = adb-manager
DESTDIR       = 
TARGET        = adb-manager


first: all
####### Build rules

adb-manager:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: adb-manager.pro ../../../../.programas/qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf ../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/unix.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/linux.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/qconfig.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/default_post.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resources.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/moc.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/yacc.prf \
		../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/lex.prf \
		adb-manager.pro \
		qml.qrc
	$(QMAKE) -o Makefile adb-manager.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/spec_pre.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/unix.conf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/linux.conf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/sanitize.conf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/gcc-base.conf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/g++-base.conf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/common/g++-unix.conf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/qconfig.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt_functions.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt_config.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/toolchain.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/default_pre.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resolve_config.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/default_post.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qml_debug.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/warn_on.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qt.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resources_functions.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/resources.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/moc.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/unix/opengl.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/unix/thread.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/qmake_use.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/file_copies.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/exceptions.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/yacc.prf:
../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/lex.prf:
adb-manager.pro:
qml.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile adb-manager.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile adb-manager

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents run_command.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp run_command.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../../../.programas/qt/5.15.2/gcc_64/bin/rcc \
		sqlDatabase.js \
		adbCommands.js \
		MainPage.qml \
		main_old.qml \
		mainLogic.js \
		SettingsPage.qml \
		Debug.qml \
		main.qml \
		scripts/adb_wifi_config.sh \
		scripts/conectar.sh \
		scripts/desconectar.sh \
		scripts/data_import.sh \
		imagens/loading-buffering.gif \
		ScreenShots/DeviceAttached.png \
		ScreenShots/MainScreen.png \
		ScreenShots/AddDeviceScreen.png
	/home/gabriel/.programas/qt/5.15.2/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h ../../../../.programas/qt/5.15.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_run_command.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_run_command.cpp
moc_run_command.cpp: run_command.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QObject \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QProcess \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qprocess.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QDebug \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qset.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		moc_predefs.h \
		../../../../.programas/qt/5.15.2/gcc_64/bin/moc
	/home/gabriel/.programas/qt/5.15.2/gcc_64/bin/moc $(DEFINES) --include '/home/gabriel/Projetos/Develop/Qt Creator/ADB Manager/moc_predefs.h' -I/home/gabriel/.programas/qt/5.15.2/gcc_64/mkspecs/linux-g++ -I'/home/gabriel/Projetos/Develop/Qt Creator/ADB Manager' -I/home/gabriel/.programas/qt/5.15.2/gcc_64/include -I/home/gabriel/.programas/qt/5.15.2/gcc_64/include/QtQuick -I/home/gabriel/.programas/qt/5.15.2/gcc_64/include/QtGui -I/home/gabriel/.programas/qt/5.15.2/gcc_64/include/QtQmlModels -I/home/gabriel/.programas/qt/5.15.2/gcc_64/include/QtQml -I/home/gabriel/.programas/qt/5.15.2/gcc_64/include/QtNetwork -I/home/gabriel/.programas/qt/5.15.2/gcc_64/include/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include run_command.h -o moc_run_command.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../../.programas/qt/5.15.2/gcc_64/include/QtGui/QGuiApplication \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtGui/qguiapplication.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qeventloop.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtGui/qinputmethod.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qset.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsize.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmargins.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/QQmlApplicationEngine \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmlengine.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qurl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qurlquery.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qjsengine.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qjsvalue.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qtqml-config.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmldebug.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqml.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmlprivate.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmllist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qpointer.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmetaobject.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmlerror.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/QQmlContext \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtQml/qqmlcontext.h \
		run_command.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QObject \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QProcess \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qprocess.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

run_command.o: run_command.cpp ../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QCoreApplication \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qflags.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstring.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qchar.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobject.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qpair.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvector.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qeventloop.h \
		run_command.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QObject \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QProcess \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qprocess.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qhash.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/QDebug \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qmap.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qset.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../../../.programas/qt/5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o run_command.o run_command.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_run_command.o: moc_run_command.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_run_command.o moc_run_command.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/adb-manager/bin || mkdir -p $(INSTALL_ROOT)/opt/adb-manager/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/adb-manager/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/adb-manager/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/adb-manager/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

